### ISSUE TITLE
Can't connect with AntennaPod

### ISSUE THREAD

**Issue by JamesG3D** [kd2org/opodsync#55] opened 2024-09-28 22:48 UTC
Seems to have an ssl issue 🤔

![Screenshot_20240929_113758_AntennaPod](https://github.com/user-attachments/assets/c07a2c96-0ade-4a8c-916f-6e65ac8eb2d0)

```
opodsync  | [8] [Sat Sep 28 22:38:07 2024] 192.168.1.38:60922 Accepted
opodsync  | [8] [Sat Sep 28 22:38:07 2024] 192.168.1.38:60922 Invalid request (Unsupported SSL request)
opodsync  | [8] [Sat Sep 28 22:38:07 2024] 192.168.1.38:60922 Closing
```

**Comment by bohwaz** [comment] 2024-09-29 16:15
This is most likely an issue caused by you trying to make a HTTPS connection to a HTTP-only server. opodsync doesn't provide SSL support. If you want SSL you need to provide by yourself, for example by creating a reverse proxy in front. But this out of scope of this project.

**Closed by bohwaz** 2024-09-29 16:15 UTC

**Comment by Paker30** [comment] 2024-10-05 17:21
@JamesG3D Try to login like this:
> http://192.168.1.2:8080

It could be your client by default tries to connect via HTTPS
